### ISSUE TITLE
Follow OS Theme

### ISSUE THREAD

**Issue by xmha97** [ranobe-org/ranobe#12]
![Screenshot_2023-02-08-00-46-20-532_org.ranobe.ranobe.jpg](https://user-images.githubusercontent.com/23485114/217368228-826bcffb-2e0a-45cd-947f-4bd9b1fcc0d5.jpg)

Please add an item to follow the system theme.

**Comment by AP-Atul** [comment]
Ok. Will do that.

**Comment by xmha97** [comment]
Thanks 👍
