### ISSUE TITLE
History and Favorites

### ISSUE THREAD

**Issue by userkilled** [ranobe-org/ranobe#16]
How about adding favorites and a history section to keep your reading list?

It reminds me something of Kotatsu,(Just because of the interface) but you can only read the manga there. 
https://github.com/KotatsuApp/Kotatsu

Great job. Thank you

**Comment by userkilled** [comment]
How about leaving a bookmark or a note so you can come back to it. Since the reading method is vertical, so far I've noticed.

**Comment by AP-Atul** [comment]
There will be a feature which track which chapter is read/completed, so the `Read` button on details screen will change to `Continue` and it can open the last read chapter
