### ISSUE TITLE
Customize: Book sources

### ISSUE THREAD

**Issue by Pantyhose-X** [ranobe-org/ranobe#18]
Set your own rules to capture web data

- [ ] Need to do crawl data rules framework, ---Only a few specific rules are needed to define the different pages.

- [ ] Allow users to write their own rules.  ---This way any website can be made into Book sources

- [ ] Import rules via `.json` and `.toml` formats, ---Import via network or local

Other
( Read Light Novel, Vip Novel, Light Novel Btt, Light Novel, Light Novel Pub, Ranobehub, All Novel, AzyNovel ) 
Imported via `.json` and `.toml` 

Ranobe Originals  ---Ranobe Originals you hold should be built-in

**Comment by AP-Atul** [comment]
I know that you are referring to `legado`. I need to see a sample `.json` or `.toml` file of rules to consider how we can use that. If you can post more info would be great.

**Comment by Pantyhose-X** [comment]
This is the book source they made https://raw.githubusercontent.com/gedoor/gedoor.github.io/master/blog/2022-09-01-2213/9%E6%9C%88%E4%BB%BD%E4%B9%A6%E6%BA%90-%E4%B8%80%E7%A8%8B.json

This is the book source they made https://raw.githubusercontent.com/gedoor/gedoor.github.io/master/blog/2022-09-01-2213/9%E6%9C%88%E4%B9%A6%E6%BA%90-namofree.txt

One-click importOne-click import http://yuedu.miaogongzi.net/gx.html

web book source editor https://github.com/gedoor/legado_web_source_editor
[Legado Book Source Rules Explained](https://alanskycn-gitee-io.translate.goog/teachme/Rule/source.html?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp)

**Comment by Pantyhose-X** [comment]
ranobe is equivalent to an engine, book source is equivalent to a mods

**Comment by Pantyhose-X** [comment]
By that I mean putting "one or more book source codes" in a .lua or other format file. This way you can import book sources from the web or locally.

Just like a game loading mods, If you do not understand how the game loads mods you can look at https://github.com/minetest/minetest

**Comment by Zig-Rust-Odin** [comment]
Like in the video.

https://github.com/mihonapp/mihon/assets/169121286/51cf3e98-29bf-4aa7-bf17-830c05af492f

can be referred [Legado](https://github.com/gedoor/legado/blob/master/English.md)>Sources management>Import online> 
```https://raw.githubusercontent.com/Zig-Rust-Odin/pixel9/main/comicsSource.json```
