### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [ranobe-org/ranobe#3]
First, thanks for making your app available openly! I've looked around, but I could not find a license mentioned – so it seems to be "all rights reserved". Would you mind choosing a license for your project, or maybe have just forgotten to mention it? If you're still unsure, please take a look at [SPDX](https://spdx.org/licenses/) and pick one approved by OSI/FSF. Thanks in advance!

**Comment by IzzySoft** [comment]
Wonderful, thanks! Just added your app to my repo then, it will [show up here](https://apt.izzysoft.de/fdroid/index/apk/org.ranobe.ranobe) with the next sync around 7 pm UTC. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there e.g. from your Readme. And if you wish, I can provide you the metadata used to set it up there in [Fastlane format](https://gitlab.com/-/snippets/1895688) with a PR, so you can control how your app is presented (fastlane would then be pulled along with future updates, which btw are checked for once a day).

**Comment by AP-Atul** [comment]
Added via #6

**Comment by IzzySoft** [comment]
Thanks! Enabled it in the config here so it will be checked with each update. Let's see if the list renders fine (you've used an indent of 2 spaces for the languages, IIRC to increase the level it would need 4 spaces – the next update will tell). Listing is live now with the metadata I edited yesterday (I e.g. de-framed the screenshots to make better use of the small screen estate on smartphone screens) – next round it will use yours. Now looking forward to the badge showing up here :smile:
